# Generated by Django 4.2.2 on 2023-12-22 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newsstory_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsstory',
            old_name='image_url',
            new_name='img_url',
        ),
    ]
